### ISSUE TITLE
Logging in no longer grabs active streams.

### ISSUE THREAD

**Issue by Laneya** [canaltinova/Twitch-Live#6]
Hey bro, probably due to a recent Firefox update, Twitch-Live is now always showing "There are no live streams." in the active streams window. Tried different accounts / reinstall / fresh Firefox, but it just doesn't grab any live streams anymore. It was working perfectly few weeks back. Thanks for your time!

**Comment by canova** [comment]
It might be related to Twitch API, I didn't updated this app lately and Twitch is in transition to API v5. I'll investigate the source of this problem. Thanks for reporting it! I need to update this add-on but there is a problem. Mozilla Add-ons website doesn't accept apps with Angular 1.x library anymore due to security issues. I need to rewrite front-end with React first. So it may take some time to solve and publish this :/

**Comment by canova** [comment]
Fixed this problem with last commit. But like I said, still I need to rewrite front-end part with React to be able to publish. But if you don't want to wait, you can build your own add-on with build instructions at the home page. Thanks for reporting it again!

**Comment by Laneya** [comment]
Thanks man, appreciate your work!

**Comment by garoto** [comment]
Chiming in to say that I just installed the extension from AMO, and from what I can tell, the "login" function isn't working anymore. Nothing shows up on my live feed.

**Comment by canova** [comment]
@garoto You're right. I still need to re-write some parts in React instead of Angular 1.X to be able to push new version to AMO. I'll try to do it as soon as possible.
Until that time you can build your own Twitch Live add-on from this source code if you want.

Thanks for your feedback!
